### ISSUE TITLE
Weird `tagfiles()` behavior

### ISSUE THREAD

**Issue by azure-satellite** [xolox/vim-easytags#114]
I don't think this issue goes here, but I don't know how to submit an issue to whatever bug tracker they use with Vim. Since I was looking at the code and saw that this plugin uses Vim's `tagfiles()` function, I thought @xolox could enlighten me. The issue is that Vim's `tagfiles()` function in my machine (7.4.488 with OS X 10.9.5) will only return the last entry in the `&tags` variable. Any idea why might this be?

**Comment by azure-satellite** [comment]
Nevermind, for anyone who might encounter this issue the problem is that `tagfiles()` will
1. Parse `&tags`
2. Only include files in the list if they exist
Leaving this open for the @xolox to close it. Maybe it will be useful to him.

**Comment by xolox** [comment]
Hi @azure-satellite. I agree the behavior of Vim's `tagfiles()` function can be confusing, however it is documented, although in a somewhat obscure fashion:

* The documentation of the [tagfiles() function](http://vimdoc.sourceforge.net/htmldoc/eval.html#tagfiles()) states:

 > Returns a List with the file names used to search for tags for the current buffer.  **This is the 'tags' option expanded.**

* The documentation of the ['tags' option](http://vimdoc.sourceforge.net/htmldoc/options.html#'tags') states:

 > The `tagfiles()` function can be used to get a list of the file names actually used.

The text *"the file names actually used"* implies that this only concerns existing tags files, but it is very implicit. So as I said, it's documented behavior, although it's a bit obscure. I will close this issue now because I don't think I can change anything about this.
