### ISSUE TITLE
ignore the vimrc file

### ISSUE THREAD

**Issue by casertap** [xolox/vim-easytags#126]
My vimrc needs 15seconds to save.
Is it possible to disable easytags for some specific file?

Thanks,
Awesome plugin.

**Comment by xolox** [comment]
Are you sure this doesn't happen when editing any Vim script file, as in this issue is not specific to your vimrc script specifically but to Vim scripts in general?

Anyway, some hints:
1. As documented [in the readme](https://github.com/xolox/vim-easytags#vim-easytags-is-slow) you can run the following command to get timing output:
   
   ``` vim
   :call xolox#easytags#why_so_slow()
   ```
   
   I'd be interested to see the results :-).
2. By adding the following command to your vimrc script you should be able to disable automatic tags updates only for your vimrc script:
   
   ``` vim
   autocmd BufReadPost ~/.vimrc let b:easytags_auto_update = 0
   ```
   
   Of course the `~/.vimrc` pathname needs to match your actual vimrc script, e.g. on Windows it should probably be `~\_vimrc` instead (IIRC).

I hope this helps.

**Comment by casertap** [comment]
Hi @xolox thanks for your answer.
I decided to switch to async write.
It works fine now.
I think the solution 2 is a great solution thanks.
