### ISSUE TITLE
Change "go to definition" shortcut

### ISSUE THREAD

**Issue by ricpelo** [xolox/vim-easytags#130]
Currently, the "go to definition" shortcut is Ctrl-]. It's very hard to use in my Spanish keyboard, because the ] key needs to be used with AltGr, so the final shortcut is Ctrl-AltGr-]. Is there a way to change that shortcut?

**Comment by xolox** [comment]
As an example, add the following to your vimrc script:

``` vim
map <F5> <C-]>
```

This creates a (normal mode) key mapping that makes the `F5` key do the same thing that the `Control-]` combination does. To achieve the same effect from insert mode:

``` vim
imap <F5> <C-o><C-]>
```

Now to make either of these practically usable you need to decide what key combination you want to use (instead of `F5`). If you run the Vim command `:help key-mapping` you'll get a Vim help file explaining the  basics. Good luck!

**Comment by ricpelo** [comment]
Thank you very much!
