### ISSUE TITLE
Using easytags with jsctags instead of exuberant ctags

### ISSUE THREAD

**Issue by jamesla** [xolox/vim-easytags#136]
I'm having a lot of trouble getting easytags to use jsctags instead of ctags. I'm struggling to find any detailed documentation on this so a lot of it has been trial and error.

I have jsctags installed and ctags is not installed.

When I open vim I get the error that exuberent ctags is not installed (obviously intentional) and easytags doesn't seem to load properly as I can't use :UpdateTags.

Is anybody able to point me in the right direction to get easytags and jsctags to play nice? Even if I could just get a single functional .vimrc I could probably figure it out from there.

```
let g:ycm_collect_identifiers_from_tags_files = 1
set tags=./.vimtags;
let g:easytags_cmd = '/Users/james/.nvm/versions/node/v5.5.0/bin/jsctags'
let g:easytags_file = '~/.vimtags'
let g:easytags_updatetime_warn = 0
let g:easytags_events = ['BufReadPost', 'BufWritePost']

let g:easytags_languages = {
      \   'javascript': {
      \       'cmd': g:easytags_cmd,
      \       'args': [],
      \       'fileoutput_opt': '-f',
      \       'stdout_opt': '-f-',
      \       'recurse_flag': '-R'
      \   }
  \}
```

**Comment by xolox** [comment]
First things first:
- The vim-easytags plug-in was never intended to be usable when Exuberant Ctags isn't installed. This explains why the error message is there and why the plug-in isn't properly loaded when Exuberant Ctags isn't available.
- Support for alternative tag generators was intended to be used as an addition to Exuberant Ctags, not a replacement.

Now for a more general response that may explain the difficulties you're encountering:
- The support for alternative tag generators was (kind of) bolted on top of vim-easytags:
  - The feature was added in a pull request and it seemed like a nice addition at the time so I accepted the changes.
  - I don't use the feature myself (I have no reason to do so) which means it doesn't receive the attention it needs to be fully fleshed out and intuitive enough to work mostly "out of the box".
- Parts of the vim-easytags plug-in depend on additional features (e.g. metadata) that Exuberant Ctags provides and alternative tag generators don't provide this metadata:
  - This complicates further improvements to the vim-easytags plug-in (in fact it's one of several things that has stifled further development).
  - This also explains why alternative tag generators don't integrate (as) well (as I would like) with the vim-easytags plug-in.

I understand that none of this really helps you to get closer to your goal, but it's all I can do for now. I have about 40 open source projects and vim-easytags has been working fine for me for the past few years (i.e. my use cases have been covered) so it doesn't receive a lot of new development (which is what would help to make alternative tags backends easier to use).

**Comment by xolox** [comment]
Here's an attempt to provide you with some more productive hints (because despite my lack of time to maintain 40+ projects, ideally I like to make every single user of my projects a happy user - it's just not always possible):
- Make sure Exuberant Ctags _is installed_ even if you only intend to edit JavaScript files, because vim-easytags will not work without it and this is not going to change (it's inherent in the design of the plug-in). Also make sure `g:easytags_cmd` doesn't point at `jsctags`.
- Now try to get `jsctags` working for JavaScript files by defining the `g:easytags_languages` variable. You can open a JavaScript file in Vim and then run `:verbose UpdateTags` to get (a lot of) information about what is happening internally, for example to see exactly what external command is being run. If the messages scroll off your screen before you can read them you can use the Vim command `:messages` to review the messages.

If you persist and succeed to get things working, it might be nice to document the steps you needed. If you're willing to help I would be glad to update the README with any additional information that you've learned while integrating `jsctags`.

**Comment by Stratus3D** [comment]
@jamesla did you ever get jsctags working in vim? I'm trying to do the same thing, but with doctorjs.

**Comment by jamesla** [comment]
No I was keen too but never ended up finding any spare time.

**Comment by alex-shamshurin** [comment]
I did it work with `jsctags` by changing some code which generate command line string from config in `autoload/xolox/easytags.vim` and now it works. Of course It could break some functionality for other libs which depends upon  `g:easytags_languages` options, but for `jsctags` it works. For person who knows vim lang (I don't) it's very easy to make the complete solution.

```
let cmdline = [program]
call add(cmdline, xolox#misc#escape#shell("-f | sed '/^$/d' | sort"))
```

And config is 
```
let g:easytags_languages = {
\   'javascript': {
\     'cmd': 'jsctags',
\       'args': [],
\   }
\}

```
